config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, :only => [:show]

  resources :events, :only => [:show, :new, :create, :destroy, :edit, :update, :index] do

    collection do #events/
      post 'filtered'
      post 'search'
    end

    member do #event/:id/ with :id passed in params[:id]
    end

    post 'follow', to: 'socializations#follow'
    post 'unfollow', to: 'socializations#unfollow'
  end

  roles = [:default, :private, :public, :owner]
  resources :comments, :only => [:create, :destroy, :show] do
    roles.each do |role|
      patch "set_#{role}", on: :member, as: "set_#{role}"
    end
  end

  get 'comments#paginate', controller: "comments", action: "paginate"

  

  
  resources :tags, :only => [:show, :create, :destroy, :index]

  get 'schedule/list'

  get 'schedule/calendar'
  get 'schedule/calendar', as: 'schedule'
  get '/schedule', to: redirect('schedule/calendar') 

  match '/feed',       controller: 'static_pages', action: 'feed',        via: [:get, :post], as: 'feed'
  match '/saved',      controller: 'static_pages', action: 'saved',       via: [:get, :post], as: 'saved'
  match '/activities', controller: 'static_pages', action: 'activities',  via: [:get, :post], as: 'activities'
  get '/activities/event/:id', to: 'static_pages#activity_detail'
  
  root 'static_pages#feed'

  get '/access_error', to: 'errors#access'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get "*any", via: :all, to: "errors#not_found"

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_events, only: [:feed, :saved, :activities]

  def saved
  	@events = @events.saved_for(current_user).deef

    respond_to do |format|
      format.html { 
          render "static_pages/feed" 
      }
      format.js {
          render "static_pages/_feed.js.erb", 
          locals: 
          {
              item_partial: "events/event",
              items: @events
          }
      }
    end

  end

  def feed
    @events = @events.not_past.deef

    respond_to do |format|
      format.html {
          render "static_pages/feed"
      }
      format.js {
          render "static_pages/_feed.js.erb",
          locals: 
          {
              item_partial: "events/event",
              items: @events
          }
      }
    end
  end

  def activities
    @events = @events.where(id: (current_user.followees(Event) | current_user.events)).by_newest_activity

    respond_to do |format|
      format.html { 
          render "static_pages/activities" 
      }
      format.js { 
          render "static_pages/_feed.js.erb",  
          locals: 
          {
              item_partial: "activities/list_short",
              items: @events
          }
      }
    end

  end

  def activity_detail
    event = Event.find(params[:id])
    activities = PublicActivity::Activity.where(owner: event ).order("created_at DESC")

    respond_to do |format|
      format.js { 
          render partial: "activities/detail",
          locals: 
          {
              event: event,
              activities: activities
          }
      }
    end
  end

  private

    def set_events
      @events = Event.page(1)
      if params[:search]
        @events = @events.search(params[:search])
      end
      if params[:pages]
        @events = @events.pages(params[:pages])
      end
      if params[:page]
        @events = @events.page(params[:page])
      end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_activity_list.html.erb
<%= render partial: 'events/event', 
	locals: 
	{ 
		event: event,
		svg_thn: 'svg/icons/letterx.svg',
		link: event,
		data: { detail: true } 
	} 
%>

<%= 
content_tag :div,
class: "activity-list col h4", 
data: {} do
%>
  <%= render_activities(activities, layout: :activity) %>
<% end %>

app/views/static_pages/_activity_list.js.erb
var $deselected = $(".activities.feed > [data-drop], [data-scroll-url]");
var $selected = $("<%= j render partial: 'static_pages/activity_list.html.erb', locals: {event: event, activities: activities} %>");

$deselected.addClass("hidden");
$(".activities.feed").prepend($selected);
window.location.hash = '<%= "detail" %>'; /* event.id.to_s */

$(document).trigger("scroll:stop");
$(".svg-link").on("click",
	function()
	{
		$(".svg-link").off("click");
		$selected.detach();
		$deselected.removeClass("hidden");
		$(document).trigger("scroll:start");
		window.location.hash = '';
	}
);

app/views/static_pages/_feed.js.erb
/*
	if you wanted to break this into two:
	1. separate scroll partial from js
	2. reload entire scroll partial for search
	3. js checks the on/off parameter set by loading the partial
*/
<% if params[:search] %>
	$('[data-scroll-content]').html("<%= j render(partial: item_partial, collection: items, format: 'html', as: items.take.class.name.downcase.to_sym) %>");
<% elsif params[:page] %>
	$('[data-scroll-content]').append("<%= j render(partial: item_partial, collection: items, format: 'html', as: items.take.class.name.downcase.to_sym) %>");
<% end %>

$('[data-scroll-url]').replaceWith("<%= j scroll_link(items) %>");

$(document).trigger("callbacks:reset");

app/views/static_pages/_feed2.js.erb
$('[data-scroll-link]').attr('data-current', '<%= items.current_page %>');
$('[data-scroll-link]').attr('data-total', '<%= items.total_pages %>');
<% if (items.current_page == items.total_pages) %>
  $('[data-scroll-link]').hide();
  $(document).trigger("scroll:off");
<% else %>
  $('[data-scroll-link] a').attr('href', '<%= url_for(page: items.current_page + 1) %>');
<% end %>

<% items.each do |item| %>
	$('[data-scroll-content]').append("<%=j render partial: partial, locals: {item.class.name.downcase.to_sym => item} %>");
<% end %>

app/views/static_pages/_search.html.erb
<%= form_tag url, remote: true, class: 'search row h2' do %>
  <%= text_field_tag :search, params[:search], placeholder: "search" %>
  <%= hidden_field_tag :items, local_assigns[:items] || "" %>
  <%= yield if block_given? %>
  <%= submit_tag '>>' %>
<% end %>

app/views/static_pages/activities.html.erb
<%= render "activities/feed" %>

app/views/static_pages/activity_feed.html.erb
<%= form_tag url_for(controller: 'events', action: 'search', target: 'activities'), remote: true, 
	class: 'activity search row h2' do %>
  <%= hidden_field_tag :items, @events.pluck(:id).join(',') %>
  <%= text_field_tag :search, params[:search], 
  placeholder: "render partial: 'events/activities', collection: @events, as: :event" %>
  <%= submit_tag '>>' %>
<% end %>

<div class="activity-feed feed col" data-search-target="1" data-scroll-content="1">

		<% @events.each do |event| %>
				<%= render partial: 'events/event', 
					locals: 
					{ 
						event: event,
						svg_thn: 'svg/test/arrow_3.svg',
						link: false,
						classes: "drop-event",
						data: drop_snd(event.id).merge({id: event.id})
					} 
				%>
				<%= content_tag :div,
					class: "activity-list col h4", 
					data: drop_rcv(event.id) do %>

				  	<%= render_activities(
					  	event.activities.order(:role, :created_at).page(1).per(10), 
					  	layout: :activity 	)%>

				  	<% if (event.activities.count > 10) %>
				  		<%= link_to "#{event.activities.count - 10} more...", 
				  			remote: true, 
				  			controller: "static_pages", 
				  			action: "activity_list", 
				  			id: event.id %>
					<% end %>
				<% end %>
		<% end %>
</div>

<%= render partial: "shared/scroll", locals: {items: @events} %>

app/views/static_pages/feed.html.erb
<div id="bar-b" class="nav-bar row h2">
	<%= link_selpage feed_path, class: 'item' do %> 
		explore
	<% end %>
	|
	<%= link_selpage saved_path, class: 'item' do %> 
		my schedule
	<% end %>
</div>

<%= render 'events/feed' %>

<%= render partial: 'shared/scroll', locals: {items: @events} %>

app/views/static_pages/updates.html.erb
<section>
	<%= render_activities(@activities, layout: :activity) %>
</section>