config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, :only => [:show]

  resources :events, :only => [:show, :new, :create, :destroy, :edit, :update, :index] do

    collection do #events/
      post 'filtered'
      post 'search'
    end

    member do #event/:id/ with :id passed in params[:id]
    end

    post 'follow', to: 'socializations#follow'
    post 'unfollow', to: 'socializations#unfollow'
  end

  roles = [:default, :private, :public, :owner]
  resources :comments, :only => [:create, :destroy, :show] do
    roles.each do |role|
      patch "set_#{role}", on: :member, as: "set_#{role}"
    end
  end

  get 'comments#paginate', controller: "comments", action: "paginate"

  

  
  resources :tags, :only => [:show, :create, :destroy, :index]

  get 'schedule/list'

  get 'schedule/calendar'
  get 'schedule/calendar', as: 'schedule'
  get '/schedule', to: redirect('schedule/calendar') 

  match '/feed',       controller: 'static_pages', action: 'feed',        via: [:get, :post], as: 'feed'
  match '/saved',      controller: 'static_pages', action: 'saved',       via: [:get, :post], as: 'saved'
  match '/activities', controller: 'static_pages', action: 'activities',  via: [:get, :post], as: 'activities'
  get '/activities/event/:id', to: 'static_pages#activity_detail'
  
  root 'static_pages#feed'

  get '/access_error', to: 'errors#access'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get "*any", via: :all, to: "errors#not_found"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Filterable
  include PublicActivity::Common
  include ActionView::Helpers::TextHelper

  belongs_to :root, :polymorphic => true
  belongs_to :commentable, :polymorphic => true
  belongs_to :user

  has_many :comments, -> (comment) { where(role: "reply", root: comment.root) },
    as: :commentable,
    dependent: :destroy
    
  has_many :activities, 
    as: :trackable, 
    class_name: 'PublicActivity::Activity',
    dependent: :destroy

  validate :commentable_valid?
  validates :user_id, presence: true
  validates :commentable_id, presence: true
  validates :role, presence: true
  validates :comment, presence: true, length: { maximum: 240 }

  # ----- could be class method
  scope :deef, -> { order("updated_at DESC", "created_at DESC") }
  # ----- #

  # ----- simplifies ajax? (unused?)
  scope :freshest_by_commentable, -> { order("created_at DESC", "commentable_id DESC") }
  scope :freshest_by_root, -> { order("created_at DESC", "root_id DESC") }
  # ----- #

  # ----- could be a presenter method
    paginates_per 6
  # ----- #

# ----- life cycle
  after_create do
    setup_params
    activity_for_create
  end

  after_save do 
    activity_for_save
  end

  before_destroy do
  end

  def setup_params
    if self.role == "default"
      self.commentable = self.root
    elsif self.role == "owner"
      self.public = true
      self.commentable = self.root
    elsif self.role == "reply"
      self.public = true
      self.root = self.commentable.root
    else
      throw "bad role for comment"
    end
  end
# -----

# ----- IMPORTANT ----- #
  # ----- fake OOP

  #- unused
  def self.roles
    c = pluck(:role).uniq
  end

  def self.role
    c = pluck(:role).uniq
    if c.size == 1
      "#{c[0]}"
    else
      "" #false
    end
  end


  #- unused?
  def self.collection(roles = nil)
    roles ||= self.pluck(:role).uniq
    Comment.where(role: roles)
  end

  #- unused?
  def collection
    self.commentable.comments.where(role: self.role)
  end


  def owner_id
    self.root.user_id
  end

  def owner
    self.root
  end

  def owner?(owner)
    (owner.id == self.owner_id)
  end
  # -----


# ----- validation ----- #
  # --- validation method
  def commentable_valid?
    if Comment.can_add_comment_to(commentable)
    else
      errors[:base] << "can't add comment to this model!"
    end
  end
  # ---

  # --- used in ^^^
  def self.can_add_comment_to(commentable)
    if commentable.class.name == "Comment"
      commentable.can_add_comment?
    elsif commentable.class.name == "Event"
      true
    else
      false # if a nested comment with role 'default'
    end
  end
  # ---

  # --- used in ^^^
  def can_add_comment?
    ( ["default"].include?(self.role) ) &&
    ( !self.is_nested? )
  end
  # ---

  # --- used in ^^^
  def is_nested?
    (self.commentable_type == "Comment")
  end
  # ---
# -------- #

# ----- public activity ----- #
  def activity_for_create
    a = create_activity key: "comment", trackable: self, owner: self.root, role: self.role, parameters: {role: self.role}
  end

  def activity_for_save
    #--- right now there's no reason not to use this
    # owner.updated_at = a.updated_at
  end
# ----- #

  def summary(length: 36)
    #truncate(self.comment, length: length, separator: /[\.\?\!\s]/)
    truncate(self.comment, length: length, separator: " ")
  end

  # ----- unused currently
  # scope :owner_comments, -> (commentable) { where(role: "owner", root: commentable, root_type: "Event", commentable: commentable, commentable_type: "Event") }
  # scope :default_comments, -> (root) { where(role: "default", root: commentable, root_type: "Event", commentable: commentable, commentable_type: "Event") }
  # scope :private_comments, -> (root) { where(role: "default", public: false, root: commentable, root_type: "Event", commentable: commentable, commentable_type: "Event") }
  # scope :public_comments, -> (root) { where(role: "default", public: true, root: commentable, root_type: "Event", commentable: commentable, commentable_type: "Event") }
  # scope :reply_comments, -> (commentable) { where(role: "default", root: commentable.root, root_type: "Event", commentable_type: "Comment") }
  # 
  # def public_comment?
  #   role == "default"             &&
  #   public == true                &&
  #   root == commentable           &&
  #   root_type == "Event"          &&
  #   commentable_type == "Event"   &&
  # end
  #
  # def public_comment?
  #   # actually, replies are also role == "default"
  #   return false unless role == "default"
  #   return false unless public == true
  #   return false unless root == commentable
  #   return false unless root_type == "Event"
  #   return false unless commentable_type == "Event"
  #   return true
  # end
  #
  # -----
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	load_resource :only => [:create, :destroy, :set_public, :set_default, :show]
	authorize_resource :only => [:create, :destroy, :show]
	before_action :set_collection, only: [:create, :destroy, :set_public, :set_default]
	

	def create
		respond_to do |format|
			if @comment.save
				format.html { redirect_to @comment.commentable }
				format.js {
					render "shared/refresh.js.erb", locals: {target: @comment.role, content: @comments.deef }
				}
			else
				format.html { redirect_to @comment.commentable, notice: @comment.errors.full_messages.join(", ") }
			end
		end
	end

	def destroy
		@comment.destroy
		respond_to do |format|
			format.html { redirect_to @comment.commentable }
			format.js {
				render "shared/refresh.js.erb", locals: {target: params[:refresh], content: @comments.deef }
			}
		end
	end


	def show
	end

	def set_public
		authorize! :set_public, @comment
		@comment.public = true
		respond_to do |format|
			if @comment.save
				format.html { redirect_to @comment.commentable }
				format.js {
					render "shared/refresh.js.erb", locals: {target: @comment.role, content: @comments.deef }
				}
			else
				format.html { redirect_to @comment.commentable, notice: @comment.errors.full_messages.join(", ") }
			end
		end
	end

	def set_default
		authorize! :set_public, @comment
		@comment.public = false
		respond_to do |format|
			if @comment.save
				format.html { redirect_to @comment.commentable }
				format.js {
					render "shared/refresh.js.erb", locals: {target: @comment.role, content: @comments.deef }
				}
			else
				format.html { redirect_to @comment.commentable, notice: @comment.errors.full_messages.join(", ") }
			end
		end
	end

	def paginate 
		role = params[:role]
		@comments = Comment.where(commentable_id: params[:id], role: params[:role])
		parameters = {controller: "comments", action: "paginate", role: role}
	    render "shared/paginate.js.erb", locals: {target: @comments.role, items: @comments.page(params[:page]).deef, parameters: parameters }
	end

	private

		def set_collection
			@comments = Comment.where(commentable: @comment.commentable, role: @comment.role)
		end

		def comment_params
			params.require(:comment).permit(:root_id, :root_type, :commentable_id, :commentable_type, :role, :user_id, :comment)
		end
end

app/helpers/comments_helper.rb
module CommentsHelper
	def self.pagi(comments, page: 1, per: 6)
		comments.page(page).per(per)
	end
end

app/views/comments/_comment.html.erb
<% if can?(:read, comment) %>
  <%= content_tag :div, class: ["item"], 
  	data: {
      id: comment.id,
      fresh: "#{ fresh?(comment) }",
      role: comment.role,
      public: comment.public,
      owner: can?(:set_public, comment)
    } do %>
    <%= link_to comment.user.name, [comment], class: "username h4" %>
    <div class="content h5">
      <%= comment.comment %>
    </div>

    <%= link_to '...', "#", remote: true, class: "h4", 
        data: {drop: "snd", drop_id: "#{comment.id}-options", drop_state: "false"} %>
    <%= content_tag :div, class: ["options", "h4"], 
        data: {drop: "rcv", drop_id: "#{comment.id}-options", drop_state: "false"} do %>
          <%= render partial: "comments/links", locals: {comment: comment} %>
    <% end %>

  <% end %>
<% end %>

app/views/comments/_feed.html.erb
<% comments = CommentsHelper.pagi(comments, page: params[:page]) %>
<%= render partial: "layouts/paginate", 
	locals: {
		items: comments, target: comments.role,
		params: {controller: "comments", action: "paginate", role: comments.role}
	}
%>
<%= content_tag :div, 
	class: ["comment-list", "col"],
	data: {refresh: comments.build.role, pagi_target: comments.build.role } do
-%>
	<%= render comments.deef %>
<% end -%>
<%= render partial: 'comments/form',
	locals: 
	{
		comment: comments.build
	} 
%>

app/views/comments/_form.html.erb
<% comment.user_id = current_user.id %>
<% if can? :create, comment %>
  <%= form_for [comment], remote: true do |f| %>

    <%= f.text_area :comment, rows: 8, class: "h4" %>
    <%= f.submit(value: "add".upcase, class: "h3") %>
    
    <%= f.hidden_field :role %>
    <%= f.hidden_field :root_id %>
    <%= f.hidden_field :root_type %>
    <%= f.hidden_field :commentable_id %>
    <%= f.hidden_field :commentable_type %>

    <span id="IMPORTANT-NOTE" style="display: none"> 
      # here for cancancan's load_and_authorize
      # remove for safety, and elsewhere in the app
      # set this param with current_user in the controller
      # THEN authorize via CanCanCan
    </span>
    <%= f.hidden_field :user_id %>

  <% end %>
<% end %>

app/views/comments/_links.html.erb
<% if can? :destroy, comment %>
  <%= link_to 'delete', [comment, :refresh => comment.role ], method: :delete, remote: true, class: "h4" %>
<% end %>

<% if can?(:set_public, comment) %>
  <% if comment.public == false %>
    <%= link_to 'publish', set_public_comment_path(comment), method: :patch, remote: true, class: "h4" %>
  <% elsif comment.public == true %>
    <%= link_to 'hide', set_default_comment_path(comment), method: :patch, remote: true, class: "h4" %>
  <% end %>
  
  <%= link_to 'reply', comment_path(comment),  class: "h4" %>
<% end %>

app/views/comments/_list.html.erb
<% comments = comments.page(params[:page]) %>
<%= render partial: 'comments/form',
	locals: 
	{
		comment: comments.build
	} 
%>
<%= render partial: "layouts/paginate", 
	locals: {
		items: comments, target: comments.role,
		params: {controller: "comments", action: "paginate", role: comments.role}
	}
%>
<%= content_tag :div, 
	class: ["comment-list", "col"],
	data: {refresh: comments.build.role, pagi_target: comments.build.role } do
-%>
	<%= render comments.deef %>
<% end -%>

app/views/comments/show.html.erb
<div id="bar-b" class="nav-bar row h2">
	<%= link_to "back", @comment.commentable %>
	<% if can?(:set_public, @comment) %>
		|
		<% if @comment.role == "default" %>
		  <%= link_to 'publish', set_public_comment_path(@comment), method: :patch %>
		<% elsif @comment.role == "public" %>
		  <%= link_to 'hide', set_default_comment_path(@comment), method: :patch %>
		<% end %>
	<% end %>
	<% if can?(:destroy, @comment) %>
		| <%= link_to 'destroy', @comment, method: :delete %>
	<% end %>
</div>

<div class="username h2">
	<%= @comment.user.name %>
</div>
<div class="content h4">
	<%= @comment.comment %>
</div>
<div class="vmn"> </div>


<% if @comment.can_add_comment? %>
	<%= content_tag :div,
		class: ["col"] do
	%>
		<%= content_tag :div,
		class: ["comment-list", "col"], 
		data: {refresh: "reply_comments"} do
		-%>
			<%= render @comment.comments %>
		<% end -%>

		<%= render partial: 'comments/form', locals:
			{ 
				comment: @comment.comments.build
			}
		%>
	<% end %>
<% end %>