config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, :only => [:show]

  resources :events, :only => [:show, :new, :create, :destroy, :edit, :update, :index] do

    collection do #events/
      post 'filtered'
      post 'search'
    end

    member do #event/:id/ with :id passed in params[:id]
    end

    post 'follow', to: 'socializations#follow'
    post 'unfollow', to: 'socializations#unfollow'
  end

  roles = [:default, :private, :public, :owner]
  resources :comments, :only => [:create, :destroy, :show] do
    roles.each do |role|
      patch "set_#{role}", on: :member, as: "set_#{role}"
    end
  end

  get 'comments#paginate', controller: "comments", action: "paginate"

  

  
  resources :tags, :only => [:show, :create, :destroy, :index]

  get 'schedule/list'

  get 'schedule/calendar'
  get 'schedule/calendar', as: 'schedule'
  get '/schedule', to: redirect('schedule/calendar') 

  match '/feed',       controller: 'static_pages', action: 'feed',        via: [:get, :post], as: 'feed'
  match '/saved',      controller: 'static_pages', action: 'saved',       via: [:get, :post], as: 'saved'
  match '/activities', controller: 'static_pages', action: 'activities',  via: [:get, :post], as: 'activities'
  get '/activities/event/:id', to: 'static_pages#activity_detail'
  
  root 'static_pages#feed'

  get '/access_error', to: 'errors#access'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get "*any", via: :all, to: "errors#not_found"

end

app/models/event.rb
class Event < ActiveRecord::Base
	include Filterable
	include Filterable::Time
	include Filterable::Text
	include Taggable
	include PublicActivity::Common
	
#----- relationships -----
	#--- socialization
	acts_as_followable
	#-----
	
	has_many :comments, as: :root, dependent: :destroy
	has_many :owner_comments, -> (event) { where(role: "owner", commentable: event) }, 
		class_name: "Comment", 
		as: :root,
		dependent: :destroy,
		after_add: :setup_comment
	has_many :list_comments, -> (event) { where(role: "default", commentable: event) }, 
		class_name: "Comment", 
		as: :root,
		dependent: :destroy
	has_many :reply_comments, -> (event) { where(role: "reply", commentable_type: "Comment") }, 
		class_name: "Comment",
		as: :root,
		dependent: :destroy

	belongs_to :user
	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings
	has_many :activities, -> { order("created_at DESC") },
		as: :owner, 
		class_name: 'PublicActivity::Activity', 
		dependent: :destroy
#-----#

#----- validations -----
	validates :user_id, presence: true
	validates :name, presence: true
	# by default the date validator checks for a valid date
	validates :starts_at, presence: true
	validates :ends_at, presence: true
	validates :ends_at, date: { after: :starts_at } 
#-----#

#----- could be a presenter method
	paginates_per 8
#-----#

#----- callbacks -----
	after_save :remove_orphaned_tags
	after_save(on: :update) do
		# called twice
		# do with 'notify_users checkbox'
	end
	after_destroy :remove_orphaned_tags
#-----#

#----- TAGS 
	def self.tagged_with(name)
		self.where(id: Tag.where(name: name).select("event_id"))
	end

	def self.tag_matches(name)
		self.joins(:tags).where(Tag.arel_table[:name].matches(name))
		# SELECT "events".* FROM "events" INNER JOIN "taggings" ON "taggings"."event_id" = "events"."id" INNER JOIN "tags" ON "tags"."id" = "taggings"."tag_id" WHERE ("tags"."name" ILIKE 'c%')
	end
#-----#

#----- COMMENTS -----#
	def setup_comment(comment)
		comment.setup_params
	end
#-----#

#----- ACTIVITIES
	def self.activities(deef: "created_at DESC")
		PublicActivity::Activity.where(owner_type: 'Event', owner_id: self.all).order(deef)
		#  										  faster -> owner_id: select(:id))
	end

	# Grab events
	# Join them with activities
	# Group by the event ('s id)
	# Now we can use max(activities.created_at) which is the newest activity.created_at for each Event
	# Then sort Events by the most recent activity.created_at in descending order
	# later, perhaps add an optional parameter to change order between DESC and ASC
	def self.by_newest_activity
		self.joins(:activities).group("events.id").order("max(activities.created_at) DESC") 
	end

	def fresh_for(user)
		self.activities.where("created_at > ?", user.last_sign_in_at).order("created_at DESC")
	end

	def fresh_for?(user)
		self.activities.where("created_at > ?", user.last_sign_in_at).any?
	end

	# def fresh_by_type(user)
	# 	f = self.activities.fresh_for(user)
	# 	f.order("activities.role").group("activities.role", "activities.id")
	# end
#-----#

#----- UNUSED -----#
	def self.to_append(events)
		self.where.not(id: events.select(:id))
	end

	def self.to_remove(events)
		events.where.not(id: self.select(:id))
	end
# ----- #

#----- PAGINATION
def self.pages(pages=1, per: 8)
	self.page(1).per(per.to_i * pages.to_i)
end
#-----

#----- INTERFACE METHODS
#- for the application's specific uses of the above class methods
#---
	def self.deef
		self.order("starts_at ASC")
	end

	def self.saved_for(user)
		followees = Follow.where( follower: user, followable_type: "Event" ).select(:followable_id)
		user_events = user.events.select(:id)
		self.in_any("id", followees, user_events)
	end

	# order determines final order
	# so this is the easiest way to do relevance
	#LOOK INTO AREL JOINS FOR TAGS SEARCH, IT'S A BIT MORE COMPLICATED
	#HOWEVER, WAIT YOU COULD DO IT THROUGH TAGS YEAH!
	def self.search_(q)
		if q.length <= 3
			n = self.arel_table[:name].matches("#{q}%")
			d = nil
			ni = self.in_name_starts_with("#{q}").arel.constraints.reduce(:and)
			di = nil
		elsif q.length <= 5
			n = self.arel_table[:name].matches("#{q}%")
			d = self.arel_table[:description].matches("#{q}%")
			ni = self.in_name_starts_with("#{q}").arel.constraints.reduce(:and)
			di = self.in_description_starts_with("#{q}").arel.constraints.reduce(:and)
		else
			n = self.arel_table[:name].matches_any(["#{q}%", "%#{q}%"])
			d = self.arel_table[:description].matches_any(["#{q}%", "%#{q}%"])
			ni = self.in_name_starts_with("#{q}").arel.constraints.reduce(:and)
			di = self.in_description_starts_with("#{q}").arel.constraints.reduce(:and)
		end
		n.or(ni).or(d).or(di)
	end

	# order determines final order
	def self.search(q)
		self.where( self.search_(q) )
	end
	#-----

#--------#



end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource only: [:show, :edit, :update, :new, :create, :destroy]

  # DON'T PASS USER_ID THROUGH FORM OR ACCEPT IT IN PARAMS
  # CHANGE THAT

  def index # unused, but still useful for tests
    @events = Event.filter(filtering_params)
  end

  def refresh_follow
    render partial: "follow_button"
  end

  def search
  end

  def create
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { redirect_to new_event_path, notice: @event.errors.full_messages.join(", ") }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @event.update(event_params)
    respond_to do |format|
      if @event.save
          format.html { redirect_to @event, notice: 'Event was successfully updated.' }
          format.json { render :show, status: :created, location: @event }
      else
          format.html { render :edit, notice: @event.errors.full_messages.join(", ") }
          format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show
    respond_to do |format|
      format.html { @comments = @event.comments.page(1) }
      format.js { 
        @comments = @event.comments.where(role: params[:target]).page(params[:page])
        render 'static_pages/_feed.js.erb', 
        locals: {
          item_partial: "comments/comment",
          items: @comments,
          target: params[:target]
        }
      }
    end
  end

  def edit
  end

  def new
  end

  private

    def event_params
      params.require(:event).permit(:name, :starts_at, :ends_at, :description, :user_id, :tag_list)
    end

    def filtering_params #unused currently
      params.permit(:starts_after, :order, :search, :name_starts_with, :name_contains)
    end
end

app/helpers/events_helper.rb
module EventsHelper
	def self.pagi(events, page: 1, per: 8, total: 1)
		events.page(page).per(per * total)
	end
end

app/views/events/_event.html.erb
<%= content_tag :div, 
  id: "#{event.id}",
  class: ["item", "row"], #+ get_local(locals: local_assigns, key: "classes", alt: []), #this could be data
  data: { past: "#{event.past?}" }.merge( local_assigns[:data] || {} ) do
%>
    <div class="image-temp svg-link"> 
      <%= inline_svg get_local(locals: local_assigns, key: "svg_thn", alt: "" ) %> 
    </div>
    <div class= "col">

        <span class="h4"> <%= date_style(event.starts_at) %> </span>
        <div class="h2 title">
          <%  link = get_local(locals: local_assigns, key: "link", alt: event) %>
          <%= link_to_unless  (link == false),  event.name.truncate(36, separator: " "),    link %> 
        </div>
        <div class="h5 username">
          <%= event.user.name %>
        </div>
        <div class="h5 username hidden">
          <%= event.description.truncate(60, separator: " ") %>
        </div>

        <span class="h4 tags"> 

            <% event.tags.limit(3).each do |tag| %>
              <%= link_to "\##{tag.name}", tag %>
            <% end %>
        
        </span>
      
    </div>
<% end %>

app/views/events/_feed.html.erb
<%= form_tag url_for(controller: controller.controller_name, action: controller.action_name), remote: true, class: 'search row h2' do %>
	<%= text_field_tag :search, params[:search], placeholder: 'search' %>
	<%= submit_tag '>>' %>
<% end %>
<div class="events feed col" data-search-target="1" data-scroll-content="1">
	<%= render @events %>
</div>

app/views/events/_form.html.erb
<%= form_for(@event, data: {form_for: "event"}) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field h2">
    <%= f.text_field :name, placeholder: "name of the event" %>
  </div>
  <div class="field h4">
    <%= f.text_area :description, placeholder: "describe the event..." %>
  </div>
  <div class="field dt h4">
    <%= f.label :starts_at, "starts:" %>
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field dt h4">
    <%= f.label :ends_at, "ends:" %>
    <%= f.datetime_select :ends_at %>
  </div>
  <div class="field h3">
    <%= f.text_field :tag_list, placeholder: "add tags" %>
  </div>
  <div class="actions h2">
    <%= f.submit %>
  </div>

  <%= f.hidden_field :user_id, :value => current_user.id %>
<% end %>

app/views/events/_index.html.erb
<table>
  <tbody>
    <% @events.each do |event| %>
      <% user = User.find(event.user_id) %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= link_to user.name, user %></td>
        <td><%= link_to 'Show', event %></td>
        <% if current_user.id == event.user_id %>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/edit.html.erb
<section>
	<%= render 'form' %>
	<br>
	<span class="options">
		<%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' }, class: "item" %> 
		|
		<%= link_to 'Back', @event %>
	</span>
</section>

app/views/events/index.html.erb
<div class="event feed col">
  <% @events.each do |event| %>
    <% user = User.find(event.user_id) %>
    <div class="item row">
      <span class="field h1"><%= link_to event.name, event %></span>
      <span class="field h2"><%= link_to user.name, user %></span>
      <div class="field tags h4"> 
        <%= event.tag_list %>
      </div>
      <span class="options row h3">
        <% if current_user.id == event.user_id %>
          <%= link_to 'Edit', edit_event_path(event) %>
          <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% else %>
          <%= render partial: "socializations/follow_button", locals: {socializable: event} %>
        <% end %>
      </span>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<section class="col">
<%= render 'form' %>
</section>

app/views/events/show.html.erb
<div id="bar-b" class="nav-bar row h2">
	<%= link_to "Calendar", url_for(
	    	:controller => 'schedule', 
	    	:action => 'calendar', 
	    	:date => @event.starts_at
    	),
    class: "item" %> |
<% if (can? :edit, @event) %>
	<%= link_to 'Edit', edit_event_path(@event), class: "item" %>
<% else %>
	<div class="item">
		<%= render partial: "socializations/follow_button", locals: {socializable: @event} %>
	</div>
<% end %>
</div>
	
<div class="show head col">
	<div class="img-main"></div>

	<div class="field date">
	  <span class="h3"> 
	  	<%= @event.starts_at.to_formatted_s(:short) %> 
	  </span>
	  <span class="h2"> 
	  	- 
	  </span> 
	  <span class="h3"> 
	  	<%= @event.ends_at.to_formatted_s(:short) %> 
	  </span>
	</div>

	<div class="field title h1"> 
		<%= @event.name %> 
	</div>

	<div class="field user h5"> 
		<% if @event.user_id == 585858 %>
			<%= link_to "DaringDanza", "#" %>
		<% else %>
	  		<%= link_to @event.user.name, @event.user %>
	  	<% end %>
	</div>

	<div class="field tags h3"> 
        <%= @event.tag_list %>
    </div>
</div>

<div class="description h3">
   <%= @event.description %>
</div>

<div class="vmn"> </div>

<section>

	<div class="row tabs">
		<%= content_tag :a, class: ["h2"], data: 
			sel_snd(0, group: 0, state: true) do %>
		updates 
		<% end %>
		<%= content_tag :a, class: ["h2"], data:
			sel_snd(1, group: 0, state: false) do %>
		questions 
		<% end %>
	</div>

	<%= content_tag :div,
	class: ["col tabbed"],
	data: sel_rcv(0, group: 0, state: true) do
	%>
		<%= render partial: 'comments/list', locals: {comments: @event.owner_comments} %>
	<% end %>

	<%= content_tag :div,
	class: ["col tabbed"],
	data: sel_rcv(1, group: 0, state: false) do
	%>

		<%= render partial: 'comments/list', locals: {comments: @event.list_comments} %>
	<% end %>

<section/>