config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, :only => [:show]

  resources :events, :only => [:show, :new, :create, :destroy, :edit, :update, :index] do

    collection do #events/
      post 'filtered'
      post 'search'
    end

    member do #event/:id/ with :id passed in params[:id]
    end

    post 'follow', to: 'socializations#follow'
    post 'unfollow', to: 'socializations#unfollow'
  end

  roles = [:default, :private, :public, :owner]
  resources :comments, :only => [:create, :destroy, :show] do
    roles.each do |role|
      patch "set_#{role}", on: :member, as: "set_#{role}"
    end
  end

  get 'comments#paginate', controller: "comments", action: "paginate"

  

  
  resources :tags, :only => [:show, :create, :destroy, :index]

  get 'schedule/list'

  get 'schedule/calendar'
  get 'schedule/calendar', as: 'schedule'
  get '/schedule', to: redirect('schedule/calendar') 

  match '/feed',       controller: 'static_pages', action: 'feed',        via: [:get, :post], as: 'feed'
  match '/saved',      controller: 'static_pages', action: 'saved',       via: [:get, :post], as: 'saved'
  match '/activities', controller: 'static_pages', action: 'activities',  via: [:get, :post], as: 'activities'
  get '/activities/event/:id', to: 'static_pages#activity_detail'
  
  root 'static_pages#feed'

  get '/access_error', to: 'errors#access'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get "*any", via: :all, to: "errors#not_found"

end

app/controllers/socializations_controller.rb
class SocializationsController < ApplicationController
  before_filter :load_socializable

  def follow
    current_user.follow!(@socializable)
    respond_to do |format|
    	format.js { render 'follow_button.js.erb', locals: {socializable: @socializable} }
    end
  end

  def unfollow
    current_user.unfollow!(@socializable)
    respond_to do |format|
    	format.js { render 'follow_button.js.erb', locals: {socializable: @socializable} }
    end
  end

private
  def load_socializable
    @socializable =
      case
      when id = params[:event_id]
        Event.find(id)
      else
        raise ArgumentError, "Unsupported socializable model, params: " + params.keys.inspect
      end
    raise ActiveRecord::RecordNotFound unless @socializable
  end  
end

app/views/socializations/_follow_button.html.erb
<% if current_user.follows?(socializable) %>
	<%= link_to 'Unfollow', event_unfollow_path(socializable), method: :post, remote: true, data: { id: socializable.id }, class: "follow-button" %>
<% else %>
	<%= link_to 'Follow', event_follow_path(socializable), method: :post, remote: true, data: { id: socializable.id }, class: "follow-button" %>
<% end %>

app/views/socializations/follow_button.js.erb
$('a[data-id="<%= j socializable.id.to_s %>"]').on("ajax:success", 
	function(e, data, status, xhr) 
	{
		$(this).replaceWith("<%= j render partial: 'socializations/follow_button', locals: {socializable: socializable} %>");
	}
);